apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: jenkins
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: akarsh1607/myapp-backend:latest
          ports:
            - containerPort: 8080
