apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: jenkins
spec:
  selector:
    app: myapp
  ports:
    - name: backend
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
